[package]
name = "cargo-touch"
version = "0.1.0"
authors = ["David McGillicuddy <david.mcgillicuddy@moixa.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
cargo_toml = "0.8.0"
env_logger = "0.7.1"
filetime = "0.2.8"
log = "0.4.8"
